config/routes.rb
Rails.application.routes.draw do

  get 'photos/index'

  get 'photos/new'

  get 'photos/create'

  get 'photos/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  resources :users;

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts, only:[:create, :destroy]

  get 'home' => 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

   root 'static_pages#home'

   resources :albums

   resources :photos, only:[:index, :new, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">RoR sample website page!</a>
    by <a href="http://www.michaelhartl.com/">ThangNguyen</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",    '#' %></li>
      <li><%= link_to "Contact",  '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
   </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#btn-right-collapse">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand"><%= link_to "SampleApp",  root_path,  id: "logo" %></div>
        </div>
        <div class="collapse navbar-collapse" id="btn-right-collapse">
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",  home_path %></li>
            <li><%= link_to "Help",  help_path %></li>
            <% if logged_in? %>
                <li><%= link_to "Users", users_path %> </li>
                <li><%= link_to "My Albums", albums_path %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Setting", edit_user_path(current_user) %></li>
                        <li><%= link_to "Log out",  logout_path,  method: :delete %></li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Log in", login_path %></li>
            <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="modal fade" id="photoModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">

                </div><!--/.modal-body-->
            </div><!-- /.modal-content -->
        </div> <!-- /.modal dialog -->
    </div><!--/.modal -->
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %> </div>
    <% end %>
    <%= yield %>

    <!-- <%= render 'layouts/footer' %> -->
  </div>
</body>
</html>